name: ToDo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Librarys
  cupertino_icons: ^0.1.3
  provider: ^4.0.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7
  date_picker_timeline: ^1.2.0
  circular_check_box: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0

flutter:

  uses-material-design: true

  assets: 
    - assets/locale/
    - assets/images/
    
  fonts:
    - family: Products
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
  